# Generated by Django 6.0.3 on 2026-04-08 10:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('production_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_logs', to=settings.AUTH_USER_MODEL)),
                ('snack_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_logs', to='inventory.snackitem')),
            ],
            options={
                'db_table': 'production_logs',
                'ordering': ['-production_date', '-created_at'],
            },
        ),
    ]
