# Generated by Django 6.0.3 on 2026-04-08 10:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SnackItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unit', models.CharField(choices=[('piece', 'Piece'), ('dozen', 'Dozen'), ('kg', 'Kilogram'), ('g', 'Gram'), ('tray', 'Tray'), ('pack', 'Pack')], default='piece', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snack_items_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'snack_items',
                'ordering': ['name'],
            },
        ),
    ]
