# Generated by Django 6.0.3 on 2026-04-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snackitem',
            name='current_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
